name: Auto Increment Major Tag and Push

on:
  push:
    branches:
      - deploy

jobs:
  tag_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Increment major version
        id: increment_major
        run: |
          latest_tag=${{ env.latest_tag }}
          IFS='.' read -ra tag_parts <<< "$latest_tag"
          major=${tag_parts[0]}
          # Increment the major version
          major=$((major + 1))
          new_tag="$major.0.0"

          # Check if the tag already exists
          if git rev-parse "refs/tags/$new_tag" >/dev/null 2>&1; then
            # Increment major again if tag exists
            major=$((major + 1))
            new_tag="$major.0.0"
          fi

          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
